### ISSUE TITLE
build failed with error: static assertion failed: Cannot format an argument

### ISSUE THREAD

**Issue by Securee** [facebook/mariana-trench#185]
When I follow the steps in  https://mariana-tren.ch/docs/build-from-source, there is the error when to compile mariana-trench:
[  1%] Building CXX object CMakeFiles/mariana-trench-library.dir/source/Access.cpp.o
In file included from /home/lzy/Security_tools/mariana-trench/install/include/fmt/format.h:48,
                 from /home/lzy/Security_tools/mariana-trench/source/Access.cpp:11:
/home/lzy/Security_tools/mariana-trench/install/include/fmt/core.h: In instantiation of ‘constexpr fmt::v9::detail::value<Context> fmt::v9::detail::make_value(T&&) [with Context = fmt::v9::basic_format_context<fmt::v9::appender, char>; T = marianatrench::Root&]’:
/home/lzy/Security_tools/mariana-trench/install/include/fmt/core.h:1777:29:   required from ‘constexpr fmt::v9::detail::value<Context> fmt::v9::detail::make_arg(T&&) [with bool IS_PACKED = true; Context = fmt::v9::basic_format_context<fmt::v9::appender, char>; type <anonymous> = fmt::v9::detail::type::custom_type; T = marianatrench::Root&; typename std::enable_if<IS_PACKED, int>::type <anonymous> = 0]’
/home/lzy/Security_tools/mariana-trench/install/include/fmt/core.h:1901:77:   required from ‘constexpr fmt::v9::format_arg_store<Context, Args>::format_arg_store(T&& ...) [with T = {marianatrench::Root&}; Context = fmt::v9::basic_format_context<fmt::v9::appender, char>; Args = {marianatrench::Root}]’
/home/lzy/Security_tools/mariana-trench/install/include/fmt/core.h:1918:31:   required from ‘constexpr fmt::v9::format_arg_store<Context, typename std::remove_cv<typename std::remove_reference<Args>::type>::type ...> fmt::v9::make_format_args(Args&& ...) [with Context = basic_format_context<appender, char>; Args = {marianatrench::Root&}]’
/home/lzy/Security_tools/mariana-trench/install/include/fmt/core.h:3206:44:   required from ‘std::string fmt::v9::format(format_string<T ...>, T&& ...) [with T = {marianatrench::Root}; std::string = std::__cxx11::basic_string<char>; format_string<T ...> = basic_format_string<char, marianatrench::Root>]’
/home/lzy/Security_tools/mariana-trench/source/Access.cpp:102:25:   required from here
/home/lzy/Security_tools/mariana-trench/install/include/fmt/core.h:1757:7: error: static assertion failed: Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt
 1757 |       formattable,
      |       ^~~~~~~~~~~
/home/lzy/Security_tools/mariana-trench/install/include/fmt/core.h:1757:7: note: ‘formattable’ evaluates to false

It seem the fmt has been upgraded to 9.1.0, if I change fmt version to 8.0.1, build successfully. So, I think  other appropriate modifications should be applied after upgrade to 9.1.0

**Comment by arthaud** [comment]
Hi @Securee, thanks for reaching out.

I think there is indeed a mistake in our cmake files and/or documentation.
For now, you need to specify `-DFMT_DEPRECATED_OSTREAM=ON` when calling `cmake` to build mariana trench.

Instead of:
```
$ cmake \
  -DREDEX_ROOT="$MARIANA_TRENCH_DIRECTORY/install" \
  -Dfmt_ROOT="$MARIANA_TRENCH_DIRECTORY/install" \
  -DCMAKE_INSTALL_PREFIX="$MARIANA_TRENCH_DIRECTORY/install" \
  ..
```
Please use:
```
$ cmake \
  -DFMT_DEPRECATED_OSTREAM=ON \
  -DREDEX_ROOT="$MARIANA_TRENCH_DIRECTORY/install" \
  -Dfmt_ROOT="$MARIANA_TRENCH_DIRECTORY/install" \
  -DCMAKE_INSTALL_PREFIX="$MARIANA_TRENCH_DIRECTORY/install" \
  ..
```

**Comment by Securee** [comment]
Thanks, @arthaud ,you are right. -DFMT_DEPRECATED_OSTREAM=ON really solves the problem.
