### ISSUE TITLE
Does not compile with latest fmt 9.1 due to lack of formatter for types

### ISSUE THREAD

**Issue by rickmark** [facebook/mariana-trench#119]
# Bug
**Bug description**
fmt/core.h:1756:3: error: static_assert failed due to requirement 'formattable' "Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt"

**Reproduction steps**
Build with fmt 9.1

**Expected behavior**
Give a clear and concise description of what you expected to happen.

**Logs**
```
Output goes here
```

**Additional context**

**Comment by 2Dai** [comment]
Same issue with fmt 8.1.1 (is the documentation and versions mentioned here : https://mariana-tren.ch/docs/contribution/ still up to date) ?
